name: API Pre Master Merge Status Check 🤖👽

on:
  push:
    branches:
      - "**"
      - "!master"
  pull_request:
    types: [opened, reopened]
    branches:
      - "master"
env:
  MAJOR: ${{ vars.MAJOR }}
  MINOR: ${{ vars.MINOR }}
jobs:
  # This workflow contains a job called "Trigger Jenkins"
  status_check:
    name: Pre Merge Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Trigger jenkins job
        uses: joshlk/jenkins-githubaction@master
        id: jenkins
        env:
            BRANCH: ${{ fromJSON('{"false":"${{ github.ref }}", "true":"${{ github.head_ref }}" }')[github.event_name == 'pull_request'] }}
        with:
          url: "http://binarybug-jenkins.centralindia.cloudapp.azure.com:8080/"
          job_name: "piggy_api_pre_deploy_check"
          username: "binarybug"
          timeout: "600"
          interval: "30"
          api_token: ${{ secrets.JENKINS_TOKEN }}
          parameters: '{"Branch_Name":"${{env.BRANCH}}","MAJOR":"${{env.MAJOR}}","MINOR":"${{env.MINOR}}"}'
      - name: Get job url
        run: echo "Job url is ${{ steps.jenkins.outputs.build_url }}"
      - name: Split Build Number From Job URL
        uses: xom9ikk/split@v1
        id: split
        with:
          string: ${{ steps.jenkins.outputs.build_url }}
          separator: /
          limit: -1
      - name: Calculate Patch Number
        id: calc
        uses: yk1028/yk1028-calc-action@v0.0.2
        with:
          x: ${{ steps.split.outputs._5 }}
          y: 1
      - name: Print Patch Number
        run: |
          echo "${{ steps.calc.outputs.minus }}"
      - name: Create Release
        uses: maxkomarychev/oction-create-release@v0.7.1
        env:
            BRANCH: ${{ fromJSON('{"false":"${{ github.ref }}", "true":"${{ github.head_ref }}" }')[github.event_name == 'pull_request'] }}
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag_name: v${{env.MAJOR}}.${{env.MINOR}}.${{ steps.calc.outputs.minus }}
          target_commitish: ${{env.BRANCH}}
          name: "${{env.BRANCH}} v${{env.MAJOR}}.${{env.MINOR}}.${{ steps.calc.outputs.minus }}"
          body: "This Release was created through github actions"
          prerelease: true
